//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University_StudentPractice.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exam()
        {
            this.Exam_Student = new HashSet<Exam_Student>();
        }
    
        public int id_exam { get; set; }
        public Nullable<System.DateTime> DateOfExam { get; set; }
        public Nullable<int> idcode { get; set; }
        public Nullable<int> RegNumber { get; set; }
        public Nullable<int> Nunber { get; set; }
        public string Auditorium { get; set; }
        public Nullable<int> Assessment { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam_Student> Exam_Student { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
