//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University_StudentPractice.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int id_exam { get; set; }
        public Nullable<System.DateTime> DateOfExam { get; set; }
        public Nullable<int> idcode { get; set; }
        public Nullable<int> RegNumber { get; set; }
        public Nullable<int> Nunber { get; set; }
        public string Auditorium { get; set; }
        public Nullable<int> Assessment { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Student Student { get; set; }
    }
}
