//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University_StudentPractice.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int id { get; set; }
        public int Number { get; set; }
        public string Title { get; set; }
        public string Degree { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
